export const CREATE_PRODUCT_SUCCESS='CREATE_PRODUCT_SUCCESS'
export const UPDATE_PRODUCT_SUCCESS='UPDATE_PRODUCT_SUCCESS'

export const ADD_TO_CART="ADD_TO_CART"
export const REMOVE_FROM_CART="REMOVE_FROM_CART"
